### ISSUE TITLE
Add interface for assigning roles to users

### ISSUE THREAD

**Issue by aw3s0me** [OSCOSS/fiduswriter#16]

**Comment by johanneswilm** [comment]
There is such an interface already! But you will need to extend it with the extra roles you came up with.

**Comment by johanneswilm** [comment]
Here is the current interface, which is accessible from the document itself and the the document overview page. At least the comment role should be added here,mpossibly also the editor role. But you might need something more complex, if you want to make it so that the original author can no longer edit the document after assigning an editor.

https://github.com/fiduswriter/fiduswriter/tree/3.0/document/static/js/es6_modules/documents/access-rights
