### ISSUE TITLE
If there is more than 3 users connected, the new connection will be freezed

### ISSUE THREAD

**Issue by aw3s0me** [OSCOSS/fiduswriter#18]
![image](https://cloud.githubusercontent.com/assets/3517287/13813413/b84529c0-eb81-11e5-8358-aba88bc3fbb7.png)

**Comment by johanneswilm** [comment]
I updated this (quickly written) Chrome webdriver script to test collaboration [1]. It lets you start an arbitrary number of clients that all type in the editor simultaneously. I was able to connect with 10 users, who all typed simultaneously to the fiduswriter.gesis.org server, and there were no issues.

I therefore expect this to be about something else, or more advanced, than just not being able to work simultaneously. For example, if one user deletes an entire part, such as the subtitle or the keyword by selecting it and deleting it, that would result in such an error. Such editing actions we should be able to prevent starting with the next release of PM (0.5).

PD: @momenifi Running this on gesis server only ever showed the last caret position of one other collaborator, even though there were nine other participants. Is this because all the users were logging in as the same user into the document?

[1] https://github.com/fiduswriter/collaboration-testing

**Comment by aw3s0me** [comment]
okay. i didnt find any bugs during selenium web driver test (10 Collaborators), only my server was quite slow. Need to build more sophisticated test.
i think the problem can be in gesis server.

**Comment by johanneswilm** [comment]
Per request, moved repository to https://github.com/fiduswriter/collaboration-testing

**Comment by momenifi** [comment]
Hallo Johannes,

Ich möchte gerne einen Selenium-Test machen. Ich habe chromedrive und test-driver.py herunterladen. Wenn ich Datei ausführe, bekomme diesen Fehler. Habe ich etwas falsch gemacht?
[cid:image001.png@01D19003.2A99F710]

VG,
Fakhri
