### ISSUE TITLE
OJS:FW add the OJS connection part of FW to the current OSCOSS version, if the main FW branch does not need it

### ISSUE THREAD

**Issue by afshinsadeghi** [OSCOSS/fiduswriter#36]
It must be confirmed by Johannes firstly.

**Comment by johanneswilm** [comment]
@sadeghiafshin I would not mind merging the general API access into FW. The way it was previously done, ti was a general access that could be connected with other software as well. 

Also, given that it's only me and @aw3s0me who have been committing to the FW sourcecode since the meeting, it doesn't seem like there is enough manpower on the part of OSCOSS to maintain a separate version of the software. 

But if I recall the meeting correctly @vinaymodi first needed to study the different parts of OJS so that we can see how it can meaningfully be put together in a way that allows for the publishing workflow that you guys have outlined. So far, I haven't quite understood what the role of OJS could be in this.

**Comment by afshinsadeghi** [comment]
I think we should create a new code other than the demo.
