### ISSUE TITLE
export SCM-KG to usable format for FW

### ISSUE THREAD

**Issue by afshinsadeghi** [OSCOSS/fiduswriter#73]
@johanneswilm what formats are best for FW 
1. to use for citing , 
2. to take it directly as an object(JSON for example)?

**Comment by johanneswilm** [comment]
I think they are both the same because the mechanism of import is run before the citation is added.

The perfect option would be the native json format bibDB, which is a format that combines a lot of the properties of biblatex/csl and prosemirror. But chances are that this format isn't supported, because I invented it and it is only used by FW so far. :)

Next best would be standard biblatex, as we have a quite good converter [1]. Third priority would be bibtex. The same converter can also read most bibtex, but may miss some of the details.

[1] https://github.com/fiduswriter/biblatex-csl-converter

**Comment by afshinsadeghi** [comment]
- made sparql query to give paper info of an author give a part of his name. 
 - what left: server ram can not handle big data files. make a script to break it into small chunks to let server upload

**Comment by afshinsadeghi** [comment]
-currently imported SCM-KG test data (from WWW conference  into http://butterbur10.iai.uni-bonn.de)
SPARQL endpoint:
http://butterbur10.iai.uni-bonn.de/SCMKG/query

I wish the SPARQL endpoint was open to everybody, not only GESIS Server. @clange  I requested that in an email from SGA.

**Comment by afshinsadeghi** [comment]
I secured the SCM-KG server, it is now accessible via username password, but the query endpoint is open for everybody to query, currently restericted and only Uni Bonn and GESIS can query it but hopefully, SGA team will remove this restriction on the SPARQL endpoint. 

Sample call to the endpoint :
 
http://butterbur10.iai.uni-bonn.de/SCMKG/query?query=SELECT%20?subject%20?predicate%20?object%20WHERE%20{%20?subject%20?predicate%20?object%20}%20LIMIT%2025

Sample showing request for username password on the server UI:

http://butterbur10.iai.uni-bonn.de/dataset.html#upload

**Comment by afshinsadeghi** [comment]
pushed the code
